gitlab_default_password: "zdYD9wLzE4jb"
gitlab_default_email: "kevin.kolk@sjtechcorp.com"
gitlab_default_token: "96vnE357fqkm4UCsvF2N"
gitlab_shared_shared_runner_token: "UxpHrgoKcVs_H_mrR46B"
gitlab_hostname: localhost