gitlab_default_password: "DevSecOps"
gitlab_default_email: "kevin.kolk@sjtechcorp.com"
gitlab_default_token: "96vnE357fqkm4UCsvF2N"
gitlab_shared_shared_runner_token: "UxpHrgoKcVs_H_mrR46B"
gitlab_runner_registration_token: '{{ gitlab_shared_shared_runner_token }}'
gitlab_hostname: gitlab.vagrant.test
gitlab_self_signed_cert_subj: "/C=US/ST=Georgia/L=Buford/O=SJ Technologies/CN={{ gitlab_hostname }}"
gitlab_ip_address: '192.168.100.10'
gitlab_runner_executor: 'docker'
# gitlab_runner_docker_volumes:
#   - "/var/run/docker.sock:/var/run/docker.sock"
#   - "/cache"
gitlab_runner_tags:
  - docker
gitlab_runner_docker_image: 'maven:3-jdk-8'
# GitLab coordinator URL
gitlab_runner_coordinator_url: "https://{{ gitlab_hostname }}/ci"
gitlab_runner_pre_clone_script: '"git config --global http.sslVerify false"'

# SSL Configuration.
gitlab_redirect_http_to_https: "true"
gitlab_ssl_certificate: "/etc/gitlab/ssl/{{ gitlab_hostname }}.crt"
gitlab_ssl_certificate_key: "/etc/gitlab/ssl/{{ gitlab_hostname }}.key"


traefik_certificates: []
traefik_docker_domain: vagrant.test
traefik_group: root
traefik_dir: /etc/traefik
traefik_networks:
  - web
traefik_user: root
traefik_state: started
traefik_hostname: "traefik.{{ traefik_docker_domain }}"
traefik_volumes: [
  "{{ traefik_dir}}/logs:/var/log/traefik"
]
traefik_https: false
traefik_https_redirect: false
traefik_debug: true