- name: Gitlab post installation tasks
  hosts: all
  connection: ssh
  become: true
  vars:
    ansible_ssh_private_key_file: /.vagrant/machines/gitlab/virtualbox/private_key
    ansible_user: vagrant
    artifact_path: ".artifacts"

  tasks:
  - name: Clear .artifacts folder
    file:
      state: "{{ item }}"
      path: "{{ artifact_path }}"
    with_items:
      - absent
      - directory

  - name: Fetch the GitLab certificate and key
    fetch:
      src: "{{ item }}"
      dest: "{{ artifact_path }}/"
      flat: yes
    with_items:
      - "{{ gitlab_ssl_certificate }}"
      - "{{ gitlab_ssl_certificate_key }}"
  