---
- name: Set concurrent option
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: '^(\s*)concurrent ='
    line: '\1concurrent = {{ gitlab_runner_concurrent }}'
    state: present
    backrefs: yes
  notify: restart_gitlab_runner

- name: Set docker privileged option
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: '^(\s*)privileged ='
    line: '\1privileged = {{ gitlab_runner_docker_privileged | lower}}'
    state: present
    backrefs: yes
  notify: restart_gitlab_runner
  
- name: Create gitlab-runner certificates folder
  file:
    path: /etc/gitlab-runner/certs/
    state: directory
    mode: 0755

- name: Copy self-signed certificate to gitlab-runner certs
  copy:
    src: "{{ gitlab_ssl_certificate }}"
    dest: /etc/gitlab-runner/certs/{{ gitlab_hostname }}.crt
    remote_src: yes